apiVersion: sonatype.com/v1alpha1
kind: NexusRepo
metadata:
  name: nexusrepo
  namespace: nexus
spec:
  config:
    data: null
    enabled: false
    mountPath: /sonatype-nexus-conf
  deployment:
    terminationGracePeriodSeconds: 120
  route:
    enabled: false
    labels: null
    name: docker
    portName: docker
  secret:
    enabled: false
    mountPath: /etc/secret-volume
    readOnly: true
  ingress:
    annotations: {}
    enabled: false
    path: /
    rules: null
    tls:
      enabled: true
      secretName: nexus-tls
  service:
    annotations: {}
    enabled: false
    labels: {}
    ports:
      - name: nexus-service
        port: 80
        targetPort: 80
  statefulset:
    enabled: false
  replicaCount: 1
  deploymentStrategy:
    type: Recreate
  nexusProxyRoute:
    annotations: null
    enabled: false
    labels: null
  tolerations: []
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    storageSize: 8Gi
  nexus:
    nexusPort: 8081
    dockerPort: 5003
    resources: {}
    imageName: >-
      registry.connect.redhat.com/sonatype/nexus-repository-manager@sha256:af94979b9e02e03c8ec593cbff3b2a41824bfcdc2815441f1e4fb55fca47e95f
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    env:
      - name: INSTALL4J_ADD_VM_PARAMS
        value: >-
          -Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M
          -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
          -Djava.util.prefs.userRoot=/nexus-data/javaprefs
      - name: NEXUS_SECURITY_RANDOMPASSWORD
        value: 'false'
    securityContext: {}
    imagePullSecret: ''
    imagePullPolicy: IfNotPresent
    service:
      type: ClusterIP
    hostAliases: []
    podAnnotations: {}